### ISSUE TITLE
XKCD font

### ISSUE THREAD

**Issue by mohammed90** [Faeranne/xkcdaas#3]
Check this repo for the proper XKCD font:
https://github.com/ipython/xkcd-font

The folder build contains the OTF file.

**Comment by Faeranne** [comment]
Already done.

**Comment by Faeranne** [comment]
turns out this is an updated version of the font I am currently using, but the library i am using doesn't support otf files.  @Mohammed90: can you get a ttf version?  I can add that to the server.

**Comment by mohammed90** [comment]
I converted it using an online tool and uploaded the resulting file to my Google Drive. Here's the link for it:
https://drive.google.com/file/d/0B4dgEwqVwcYHOUFNekM5djh1YVE/edit?usp=sharing

If you have trouble downloading it, let me know and I'll find another way to send it.
